name: Automatic Merge

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Create and Checkout Branch B
        run: |
          git checkout -b B

      - name: Merge into Branch B
        run: |
#          git pull origin B --no-ff --allow-unrelated-histories
          git merge --no-edit main

      - name: Push Changes to Branch B
        run: |
          git push origin B
